import type { Metadata } from "next";
import  localFont  from "next/font/local";
import "./globals.css";


const font = localFont({
  variable: "--font-BYekan",
  src: "../../public/fonts/BYekan/BYekan+ Bold.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
